project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources:
    - "materials/**/*"
  
website:
  title: "Corporate Financial Management"
  site-url: https://quinfer.github.io/corp-fin-mgt/
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true # This embeds all resources
    self-contained: true  # This ensures files are independent
    page-layout: full
  revealjs:
    theme: simple
    slide-number: true
    footer: "Corporate Financial Management"
    embed-resources: true
    self-contained: true
    smaller: true
    scrollable: true 