project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "materials/capitial-investment-decisions-guide.qmd"
    - "!/materials/module-handbook-old.qmd"
  resources:
    - "materials/**/*"
  
website:
  title: "Corporate Financial Management"
  site-url: https://quinfer.github.io/corp-fin-mgt/
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
    toc: true
    embed-resources: true # This embeds all resources
    self-contained: true  # This ensures files are independent
    page-layout: full
    css: _assets/css/styles.css
    mainfont: "Arial, Helvetica, sans-serif"
  revealjs:
    slide-number: true
    footer: "Corporate Financial Management"
    embed-resources: true
    self-contained: true
    smaller: true
    scrollable: true
    css: _assets/css/slides.css
    mainfont: "Arial, Helvetica, sans-serif" 